alias less='less -R'
alias grep='grep --color=auto'
alias ..='cd ../'
alias ls='exa'
alias ll='exa -alh'
alias llr='exa -alhR'
alias cl='clear'
alias zrc='vi ~/.zshrc'
alias vrc='vi ~/.vimrc'
alias arc='vi ~/.zsh/aliases.zsh'
alias tb='nc termbin.com 9999'
alias openports='ss -tulpn | grep LISTEN'
alias kn='kubens'
alias kx='kubectx'
alias cat='bat'
